### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by ccccxuannn** [hanmin0822/MisakaTranslator#233]
在添加游戏完成后，出现提示说有无法全局修复的错误

**问题描述**
在添加游戏完成的最后一步，只要一点击完成，就会提示有错误。试了几次都没用。

**应用版本**
<MisakaTranslator.2.11-debug>

**系统信息**
<Windows11 for x64>

**错误信息**
==============System Info================
System:Microsoft Windows NT 10.0.22000.0
CurrentTime:2/6/2022 11:09 AM
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.11.0.0
==============Exception Info================
ExceptionType:Non UI Thread
ExceptionName:System.Exception
ExceptionSource:TranslatorLibrary
ExceptionMessage:Patch File is not Exists.
ExceptionStackTrace:   at TranslatorLibrary.ArtificialTranslator.TranslatorInit(String patchPath, String param2) in C:\Users\Administrator\Downloads\MisakaTranslator-master\TranslatorLibrary\ArtificialTranslator.cs:line 92
   at MisakaTranslator_WPF.TranslateWindow.TranslatorAuto(String translator) in C:\Users\Administrator\Downloads\MisakaTranslator-master\MisakaTranslator-WPF\TranslateWindow.xaml.cs:line 250
   at MisakaTranslator_WPF.TranslateWindow..ctor() in C:\Users\Administrator\Downloads\MisakaTranslator-master\MisakaTranslator-WPF\TranslateWindow.xaml.cs:line 100
   at MisakaTranslator_WPF.GameGuideWindow.Next_Click(Object sender, RoutedEventArgs e) in C:\Users\Administrator\Downloads\MisakaTranslator-master\MisakaTranslator-WPF\GameGuideWindow.xaml.cs:line 118
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at MisakaTranslator_WPF.GuidePages.CompletationPage.ConfirmBtn_Click(Object sender, RoutedEventArgs e) in C:\Users\Administrator\Downloads\MisakaTranslator-master\MisakaTranslator-WPF\GuidePages\CompletationPage.xaml.cs:line 33
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at MisakaTranslator_WPF.App.Main()

[2022-06-02 11-09-10.txt](https://github.com/hanmin0822/MisakaTranslator/files/8820461/2022-06-02.11-09-10.txt)
[2022-06-02 11-09-03.txt](https://github.com/hanmin0822/MisakaTranslator/files/8820464/2022-06-02.11-09-03.txt)
[2022-06-02 11-03-50.txt](https://github.com/hanmin0822/MisakaTranslator/files/8820465/2022-06-02.11-03-50.txt)
[2022-06-02 11-03-34.txt](https://github.com/hanmin0822/MisakaTranslator/files/8820466/2022-06-02.11-03-34.txt)

**Comment by jsc723** [comment]
去翻译源设置里把人工翻译关了，人工翻译是需要指定补丁文件的
